# Form implementation generated from reading ui file 'c:\Users\markw\EECS_581\Casino\EECS-581-Project-3\src\qt-design-files\sabacc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(799, 598)
        self.graphicsView = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.graphicsView.setObjectName("graphicsView")
        self.leaveButton = QtWidgets.QPushButton(parent=Form)
        self.leaveButton.setGeometry(QtCore.QRect(10, 540, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(15)
        self.leaveButton.setFont(font)
        self.leaveButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    color: white;\n"
"}")
        self.leaveButton.setObjectName("leaveButton")
        self.StartButton = QtWidgets.QPushButton(parent=Form)
        self.StartButton.setGeometry(QtCore.QRect(90, 540, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(15)
        self.StartButton.setFont(font)
        self.StartButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #64ff00,\n"
"        stop:1 #7d9d00\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #64ff00,\n"
"        stop:1 #7d9d00\n"
"    );\n"
"    color: white;\n"
"}")
        self.StartButton.setObjectName("StartButton")
        self.bet5 = QtWidgets.QPushButton(parent=Form)
        self.bet5.setGeometry(QtCore.QRect(10, 500, 75, 24))
        self.bet5.setObjectName("bet5")
        self.bet50 = QtWidgets.QPushButton(parent=Form)
        self.bet50.setGeometry(QtCore.QRect(10, 460, 75, 24))
        self.bet50.setObjectName("bet50")
        self.dice1 = QtWidgets.QLCDNumber(parent=Form)
        self.dice1.setGeometry(QtCore.QRect(310, 10, 64, 23))
        self.dice1.setObjectName("dice1")
        self.dice2 = QtWidgets.QLCDNumber(parent=Form)
        self.dice2.setGeometry(QtCore.QRect(420, 10, 64, 23))
        self.dice2.setObjectName("dice2")
        self.bet100 = QtWidgets.QPushButton(parent=Form)
        self.bet100.setGeometry(QtCore.QRect(10, 420, 75, 24))
        self.bet100.setObjectName("bet100")
        self.rules = QtWidgets.QPushButton(parent=Form)
        self.rules.setGeometry(QtCore.QRect(90, 500, 75, 24))
        self.rules.setObjectName("rules")
        self.betAmount = QtWidgets.QLCDNumber(parent=Form)
        self.betAmount.setGeometry(QtCore.QRect(100, 460, 64, 23))
        self.betAmount.setObjectName("betAmount")
        self.sabacc_pot = QtWidgets.QLCDNumber(parent=Form)
        self.sabacc_pot.setGeometry(QtCore.QRect(360, 250, 64, 23))
        self.sabacc_pot.setObjectName("sabacc_pot")
        self.drawButton = QtWidgets.QPushButton(parent=Form)
        self.drawButton.setGeometry(QtCore.QRect(670, 430, 75, 24))
        self.drawButton.setObjectName("drawButton")
        self.swapButton = QtWidgets.QPushButton(parent=Form)
        self.swapButton.setGeometry(QtCore.QRect(670, 470, 75, 24))
        self.swapButton.setObjectName("swapButton")
        self.standButton = QtWidgets.QPushButton(parent=Form)
        self.standButton.setGeometry(QtCore.QRect(670, 510, 75, 24))
        self.standButton.setObjectName("standButton")
        self.junkButton = QtWidgets.QPushButton(parent=Form)
        self.junkButton.setGeometry(QtCore.QRect(670, 550, 75, 24))
        self.junkButton.setObjectName("junkButton")
        self.UserDialogBox = QtWidgets.QTextBrowser(parent=Form)
        self.UserDialogBox.setGeometry(QtCore.QRect(270, 551, 256, 31))
        self.UserDialogBox.setObjectName("UserDialogBox")
        self.card1 = QtWidgets.QToolButton(parent=Form)
        self.card1.setGeometry(QtCore.QRect(270, 500, 22, 22))
        self.card1.setObjectName("card1")
        self.card2 = QtWidgets.QToolButton(parent=Form)
        self.card2.setGeometry(QtCore.QRect(330, 500, 22, 22))
        self.card2.setObjectName("card2")
        self.card3 = QtWidgets.QToolButton(parent=Form)
        self.card3.setGeometry(QtCore.QRect(390, 500, 22, 22))
        self.card3.setObjectName("card3")
        self.card4 = QtWidgets.QToolButton(parent=Form)
        self.card4.setGeometry(QtCore.QRect(450, 500, 22, 22))
        self.card4.setObjectName("card4")
        self.card5 = QtWidgets.QToolButton(parent=Form)
        self.card5.setGeometry(QtCore.QRect(510, 500, 22, 22))
        self.card5.setObjectName("card5")
        self.opponents1 = QtWidgets.QPushButton(parent=Form)
        self.opponents1.setGeometry(QtCore.QRect(180, 570, 75, 24))
        self.opponents1.setObjectName("opponents1")
        self.opponents2 = QtWidgets.QPushButton(parent=Form)
        self.opponents2.setGeometry(QtCore.QRect(180, 540, 75, 24))
        self.opponents2.setObjectName("opponents2")
        self.opponents3 = QtWidgets.QPushButton(parent=Form)
        self.opponents3.setGeometry(QtCore.QRect(180, 510, 75, 24))
        self.opponents3.setObjectName("opponents3")
        self.graphicsView.raise_()
        self.UserDialogBox.raise_()
        self.leaveButton.raise_()
        self.StartButton.raise_()
        self.bet5.raise_()
        self.bet50.raise_()
        self.dice1.raise_()
        self.dice2.raise_()
        self.bet100.raise_()
        self.rules.raise_()
        self.betAmount.raise_()
        self.sabacc_pot.raise_()
        self.drawButton.raise_()
        self.swapButton.raise_()
        self.standButton.raise_()
        self.junkButton.raise_()
        self.card1.raise_()
        self.card2.raise_()
        self.card3.raise_()
        self.card4.raise_()
        self.card5.raise_()
        self.opponents1.raise_()
        self.opponents2.raise_()
        self.opponents3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.leaveButton.setText(_translate("Form", "Leave"))
        self.StartButton.setText(_translate("Form", "Start"))
        self.bet5.setText(_translate("Form", "Bet +5"))
        self.bet50.setText(_translate("Form", "Bet +50"))
        self.bet100.setText(_translate("Form", "Bet +100"))
        self.rules.setText(_translate("Form", "Rules"))
        self.drawButton.setText(_translate("Form", "Draw"))
        self.swapButton.setText(_translate("Form", "Swap"))
        self.standButton.setText(_translate("Form", "Stand"))
        self.junkButton.setText(_translate("Form", "Junk"))
        self.UserDialogBox.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.card1.setText(_translate("Form", "..."))
        self.card2.setText(_translate("Form", "..."))
        self.card3.setText(_translate("Form", "..."))
        self.card4.setText(_translate("Form", "..."))
        self.card5.setText(_translate("Form", "..."))
        self.opponents1.setText(_translate("Form", "1"))
        self.opponents2.setText(_translate("Form", "2"))
        self.opponents3.setText(_translate("Form", "3"))
