# Form implementation generated from reading ui file 'blackjack.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BlackJackScreen(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        Form.setStyleSheet("background-color: qlineargradient(\n"
"    x1:0, y1:0, x2:0, y2:1,\n"
"    stop:0 #009f00,\n"
"    stop:1 #004d00\n"
");")
        self.dealerLabel = QtWidgets.QLabel(parent=Form)
        self.dealerLabel.setGeometry(QtCore.QRect(410, 10, 301, 181))
        self.dealerLabel.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(32)
        font.setItalic(True)
        self.dealerLabel.setFont(font)
        self.dealerLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    padding-bottom: 100px\n"
"}")
        self.dealerLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dealerLabel.setLineWidth(1)
        self.dealerLabel.setObjectName("dealerLabel")
        self.playerLabel = QtWidgets.QLabel(parent=Form)
        self.playerLabel.setGeometry(QtCore.QRect(420, 380, 331, 191))
        self.playerLabel.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(32)
        font.setItalic(True)
        self.playerLabel.setFont(font)
        self.playerLabel.setAutoFillBackground(False)
        self.playerLabel.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"    padding-top: 100px;\n"
"}")
        self.playerLabel.setObjectName("playerLabel")
        self.dealButton = QtWidgets.QPushButton(parent=Form)
        self.dealButton.setGeometry(QtCore.QRect(30, 400, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(19)
        self.dealButton.setFont(font)
        self.dealButton.setStyleSheet("QPushButton {background-color: qlineargradient(\n"
"            x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #ff0000,\n"
"            stop:1 #7d0000\n"
"    );\n"
"}")
        self.dealButton.setObjectName("dealButton")
        self.betButton = QtWidgets.QPushButton(parent=Form)
        self.betButton.setGeometry(QtCore.QRect(30, 460, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(19)
        self.betButton.setFont(font)
        self.betButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(222, 255, 42, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.betButton.setObjectName("betButton")
        self.chipsNum = QtWidgets.QLabel(parent=Form)
        self.chipsNum.setGeometry(QtCore.QRect(20, 50, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(20)
        self.chipsNum.setFont(font)
        self.chipsNum.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"    x1:0, y1:0, x2:0, y2:1,\n"
"    stop:0 #7d7a7a, stop:1 #c7bfbf);\n"
"    color: black;\n"
"}")
        self.chipsNum.setObjectName("chipsNum")
        self.hitButton = QtWidgets.QPushButton(parent=Form)
        self.hitButton.setGeometry(QtCore.QRect(400, 260, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(19)
        self.hitButton.setFont(font)
        self.hitButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(57, 255, 42, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.hitButton.setObjectName("hitButton")
        self.standButton = QtWidgets.QPushButton(parent=Form)
        self.standButton.setGeometry(QtCore.QRect(610, 260, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(19)
        self.standButton.setFont(font)
        self.standButton.setStyleSheet("QPushButton {background-color: qlineargradient(\n"
"            x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #ff0000,\n"
"            stop:1 #7d0000\n"
"    );\n"
"}")
        self.standButton.setObjectName("standButton")
        self.cardGraphicsView = QtWidgets.QGraphicsView(parent=Form)
        self.cardGraphicsView.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.cardGraphicsView.setObjectName("cardGraphicsView")
        self.leaveButton = QtWidgets.QPushButton(parent=Form)
        self.leaveButton.setGeometry(QtCore.QRect(70, 520, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        self.leaveButton.setFont(font)
        self.leaveButton.setStyleSheet("QPushButton {background-color: qlineargradient(\n"
"            x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #ff0000,\n"
"            stop:1 #7d0000\n"
"    );\n"
"}")
        self.leaveButton.setObjectName("leaveButton")
        self.potNum = QtWidgets.QLabel(parent=Form)
        self.potNum.setGeometry(QtCore.QRect(20, 100, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(20)
        self.potNum.setFont(font)
        self.potNum.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"    x1:0, y1:0, x2:0, y2:1,\n"
"    stop:0 #7d7a7a, stop:1 #c7bfbf);\n"
"    color: black;\n"
"}")
        self.potNum.setObjectName("potNum")
        self.cardGraphicsView.raise_()
        self.dealerLabel.raise_()
        self.playerLabel.raise_()
        self.dealButton.raise_()
        self.betButton.raise_()
        self.chipsNum.raise_()
        self.hitButton.raise_()
        self.standButton.raise_()
        self.leaveButton.raise_()
        self.potNum.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dealerLabel.setText(_translate("Form", "Dealer\'s Hand:"))
        self.playerLabel.setText(_translate("Form", "Player\'s Hand:"))
        self.dealButton.setText(_translate("Form", "Start"))
        self.betButton.setText(_translate("Form", "Bet More"))
        self.chipsNum.setText(_translate("Form", "Your Total:"))
        self.hitButton.setText(_translate("Form", "Hit"))
        self.standButton.setText(_translate("Form", "Stand"))
        self.leaveButton.setText(_translate("Form", "Leave"))
        self.potNum.setText(_translate("Form", "Pot: "))