# Form implementation generated from reading ui file 'blackjack.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BlackJackScreen(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        Form.setStyleSheet("background-color: qlineargradient(\n"
"    x1:0, y1:0, x2:0, y2:1,\n"
"    stop:0 #009f00,\n"
"    stop:1 #004d00\n"
");")
        self.dealerLabel = QtWidgets.QLabel(parent=Form)
        self.dealerLabel.setGeometry(QtCore.QRect(20, 30, 249, 241))
        self.dealerLabel.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(32)
        self.dealerLabel.setFont(font)
        self.dealerLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    padding-bottom: 100px\n"
"}")
        self.dealerLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dealerLabel.setLineWidth(1)
        self.dealerLabel.setObjectName("dealerLabel")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(50, 280, 131, 16))
        self.label.setObjectName("label")
        self.playerLabel = QtWidgets.QLabel(parent=Form)
        self.playerLabel.setGeometry(QtCore.QRect(20, 320, 249, 221))
        self.playerLabel.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(32)
        self.playerLabel.setFont(font)
        self.playerLabel.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    padding-top: 100px;\n"
"}")
        self.playerLabel.setObjectName("playerLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dealerLabel.setText(_translate("Form", "Dealer\'s Hand:"))
        self.label.setText(_translate("Form", "[Deck of Cards here]"))
        self.playerLabel.setText(_translate("Form", "Player\'s Hand:"))
