# Form implementation generated from reading ui file '..\..\qt-design-files\menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MenuScreen(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        Form.setStyleSheet("background-color: qlineargradient(\n"
"    x1:0, y1:0, x2:0, y2:1,\n"
"    stop:0 #009f00,\n"
"    stop:1 #004d00\n"
");\n"
"")
        self.exitButton = QtWidgets.QPushButton(parent=Form)
        self.exitButton.setGeometry(QtCore.QRect(10, 520, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Charter")
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("background-color: qlineargradient(\n"
"    x1:0, y1:0, x2:0, y2:1,\n"
"    stop:0 #ff0000,\n"
"    stop:1 #7d0000\n"
");\n"
"")
        self.exitButton.setObjectName("exitButton")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(370, 50, 421, 250))
        self.label.setMinimumSize(QtCore.QSize(100, 250))
        font = QtGui.QFont()
        font.setFamily("Magneto")
        font.setPointSize(104)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0); color: #000000")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 371, 476))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.blackjackButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.blackjackButton.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(25)
        font.setKerning(True)
        self.blackjackButton.setFont(font)
        self.blackjackButton.setStyleSheet("QPushButton {\n"
"    color: rgba(50, 75, 50, 255); padding-left: -190px; \n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgba(50, 75, 50, 255); padding-left: -190px; \n"
"    background-color: rgba(255, 255, 255, 120);\n"
"}")
        self.blackjackButton.setObjectName("blackjackButton")
        self.verticalLayout.addWidget(self.blackjackButton)
        self.rouletteButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.rouletteButton.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(25)
        self.rouletteButton.setFont(font)
        self.rouletteButton.setAutoFillBackground(False)
        self.rouletteButton.setStyleSheet("QPushButton {\n"
"    color: rgba(50, 75, 50, 255); padding-left: -201px; \n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgba(50, 75, 50, 255); padding-left: -201px; \n"
"    background-color: rgba(255, 255, 255, 120);\n"
"}")
        self.rouletteButton.setObjectName("rouletteButton")
        self.verticalLayout.addWidget(self.rouletteButton)
        self.pokerButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pokerButton.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(25)
        self.pokerButton.setFont(font)
        self.pokerButton.setStyleSheet("QPushButton {\n"
"    color: rgba(50, 75, 50, 255); padding-left: -229px; \n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgba(50, 75, 50, 255); padding-left: -229px; \n"
"    background-color: rgba(255, 255, 255, 120);\n"
"}")
        self.pokerButton.setObjectName("pokerButton")
        self.verticalLayout.addWidget(self.pokerButton)
        self.sabaccButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.sabaccButton.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(25)
        self.sabaccButton.setFont(font)
        self.sabaccButton.setStyleSheet("QPushButton {\n"
"    color: rgba(50, 75, 50, 255); padding-left: -218px; \n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgba(50, 75, 50, 255); padding-left: -218px; \n"
"    background-color: rgba(255, 255, 255, 120);\n"
"}")
        self.sabaccButton.setObjectName("sabaccButton")
        self.verticalLayout.addWidget(self.sabaccButton)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(420, 270, 331, 241))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: qlineargradient(...)")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("..\\..\\qt-design-files\\assets/casino-chips-on-transparent-background-png-604786155.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exitButton.setText(_translate("Form", "Exit"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:48pt; color:#ffffff;\">StakeFree</span></p><p><span style=\" font-size:48pt; color:#ffffff;\">Casino</span></p></body></html>"))
        self.blackjackButton.setText(_translate("Form", "Blackjack"))
        self.rouletteButton.setText(_translate("Form", "Roulette"))
        self.pokerButton.setText(_translate("Form", "Poker"))
        self.sabaccButton.setText(_translate("Form", "Sabacc"))
