# Form implementation generated from reading ui file 'poker.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PokerScreen(object):
    def setupUi(self, PokerScreen):
        PokerScreen.setObjectName("PokerScreen")
        PokerScreen.resize(800, 600)
        PokerScreen.setMinimumSize(QtCore.QSize(800, 600))
        PokerScreen.setMaximumSize(QtCore.QSize(800, 600))
        PokerScreen.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        PokerScreen.setStyleSheet("background-color: qlineargradient(\n"
"    x1:0, y1:0, x2:0, y2:1,\n"
"    stop:0 #009f00,\n"
"    stop:1 #004d00\n"
");")
        self.playerHandLabel = QtWidgets.QLabel(parent=PokerScreen)
        self.playerHandLabel.setGeometry(QtCore.QRect(320, 520, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(36)
        self.playerHandLabel.setFont(font)
        self.playerHandLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.playerHandLabel.setObjectName("playerHandLabel")
        self.totalLabel = QtWidgets.QLabel(parent=PokerScreen)
        self.totalLabel.setGeometry(QtCore.QRect(10, 480, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(24)
        self.totalLabel.setFont(font)
        self.totalLabel.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #7d7a7a, \n"
"            stop:1 #c7bfbf);\n"
"            color: black;\n"
"}")
        self.totalLabel.setObjectName("totalLabel")
        self.leaveButton = QtWidgets.QPushButton(parent=PokerScreen)
        self.leaveButton.setGeometry(QtCore.QRect(10, 540, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(20)
        self.leaveButton.setFont(font)
        self.leaveButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    color: white;\n"
"}")
        self.leaveButton.setObjectName("leaveButton")
        self.opp3 = QtWidgets.QLabel(parent=PokerScreen)
        self.opp3.setGeometry(QtCore.QRect(20, 200, 91, 91))
        self.opp3.setText("")
        self.opp3.setPixmap(QtGui.QPixmap("../assets/glass_joe.png"))
        self.opp3.setScaledContents(True)
        self.opp3.setObjectName("opp3")
        self.opp2 = QtWidgets.QLabel(parent=PokerScreen)
        self.opp2.setGeometry(QtCore.QRect(690, 200, 91, 91))
        self.opp2.setText("")
        self.opp2.setPixmap(QtGui.QPixmap("../assets/king_hippo.png"))
        self.opp2.setScaledContents(True)
        self.opp2.setObjectName("opp2")
        self.opp1 = QtWidgets.QLabel(parent=PokerScreen)
        self.opp1.setGeometry(QtCore.QRect(360, 10, 91, 91))
        self.opp1.setText("")
        self.opp1.setPixmap(QtGui.QPixmap("../assets/super_macho_man.png"))
        self.opp1.setScaledContents(True)
        self.opp1.setObjectName("opp1")
        self.flop1 = QtWidgets.QLabel(parent=PokerScreen)
        self.flop1.setGeometry(QtCore.QRect(190, 190, 71, 111))
        self.flop1.setText("")
        self.flop1.setObjectName("flop1")
        self.flop2 = QtWidgets.QLabel(parent=PokerScreen)
        self.flop2.setGeometry(QtCore.QRect(280, 190, 71, 111))
        self.flop2.setText("")
        self.flop2.setObjectName("flop2")
        self.flop3 = QtWidgets.QLabel(parent=PokerScreen)
        self.flop3.setGeometry(QtCore.QRect(370, 190, 71, 111))
        self.flop3.setText("")
        self.flop3.setObjectName("flop3")
        self.turn = QtWidgets.QLabel(parent=PokerScreen)
        self.turn.setGeometry(QtCore.QRect(460, 190, 71, 111))
        self.turn.setText("")
        self.turn.setObjectName("turn")
        self.river = QtWidgets.QLabel(parent=PokerScreen)
        self.river.setGeometry(QtCore.QRect(550, 190, 71, 111))
        self.river.setText("")
        self.river.setObjectName("river")
        self.dealButton = QtWidgets.QPushButton(parent=PokerScreen)
        self.dealButton.setGeometry(QtCore.QRect(110, 540, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(24)
        self.dealButton.setFont(font)
        self.dealButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #64ff00,\n"
"        stop:1 #7d9d00\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #64ff00,\n"
"        stop:1 #7d9d00\n"
"    );\n"
"    color: white;\n"
"}")
        self.dealButton.setObjectName("dealButton")
        self.deckLabel = QtWidgets.QLabel(parent=PokerScreen)
        self.deckLabel.setGeometry(QtCore.QRect(80, 350, 71, 111))
        self.deckLabel.setText("")
        self.deckLabel.setPixmap(QtGui.QPixmap("../assets/cards/card_back.jpg"))
        self.deckLabel.setScaledContents(True)
        self.deckLabel.setObjectName("deckLabel")
        self.checkcallButton = QtWidgets.QPushButton(parent=PokerScreen)
        self.checkcallButton.setGeometry(QtCore.QRect(570, 360, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(24)
        self.checkcallButton.setFont(font)
        self.checkcallButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ffff00,\n"
"        stop:1 #7d7d00\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ffff00,\n"
"        stop:1 #7d7d00\n"
"    );\n"
"    color: white;\n"
"}")
        self.checkcallButton.setObjectName("checkcallButton")
        self.betraiseButton = QtWidgets.QPushButton(parent=PokerScreen)
        self.betraiseButton.setGeometry(QtCore.QRect(570, 410, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(24)
        self.betraiseButton.setFont(font)
        self.betraiseButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff6600,\n"
"        stop:1 #6e4e00\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff6600,\n"
"        stop:1 #6e4e00\n"
"    );\n"
"    color: white;\n"
"}")
        self.betraiseButton.setObjectName("betraiseButton")
        self.foldButton = QtWidgets.QPushButton(parent=PokerScreen)
        self.foldButton.setGeometry(QtCore.QRect(570, 460, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(24)
        self.foldButton.setFont(font)
        self.foldButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    color: white;\n"
"}")
        self.foldButton.setObjectName("foldButton")
        self.graphicsView = QtWidgets.QGraphicsView(parent=PokerScreen)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.graphicsView.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.graphicsView.setObjectName("graphicsView")
        self.potLabel = QtWidgets.QLabel(parent=PokerScreen)
        self.potLabel.setGeometry(QtCore.QRect(570, 310, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(24)
        self.potLabel.setFont(font)
        self.potLabel.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #7d7a7a, \n"
"            stop:1 #c7bfbf);\n"
"            color: black;\n"
"}")
        self.potLabel.setObjectName("potLabel")
        self.oppCount = QtWidgets.QSpinBox(parent=PokerScreen)
        self.oppCount.setGeometry(QtCore.QRect(10, 20, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(24)
        self.oppCount.setFont(font)
        self.oppCount.setStyleSheet("color: black;")
        self.oppCount.setFrame(True)
        self.oppCount.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.oppCount.setKeyboardTracking(False)
        self.oppCount.setMinimum(1)
        self.oppCount.setMaximum(3)
        self.oppCount.setProperty("value", 3)
        self.oppCount.setObjectName("oppCount")
        self.label = QtWidgets.QLabel(parent=PokerScreen)
        self.label.setGeometry(QtCore.QRect(20, 30, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: black;")
        self.label.setObjectName("label")
        self.allinButton = QtWidgets.QPushButton(parent=PokerScreen)
        self.allinButton.setGeometry(QtCore.QRect(570, 510, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Broadway Flat 3D Filled")
        font.setPointSize(36)
        font.setBold(True)
        self.allinButton.setFont(font)
        self.allinButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    font-weight: bold;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    font-weight: bold;\n"
"    border-radius: 15px;\n"
"}")
        self.allinButton.setObjectName("allinButton")
        self.oppTotal3 = QtWidgets.QLabel(parent=PokerScreen)
        self.oppTotal3.setGeometry(QtCore.QRect(20, 170, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(14)
        self.oppTotal3.setFont(font)
        self.oppTotal3.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #7d7a7a, \n"
"            stop:1 #c7bfbf);\n"
"            color: black;\n"
"}")
        self.oppTotal3.setObjectName("oppTotal3")
        self.oppTotal2 = QtWidgets.QLabel(parent=PokerScreen)
        self.oppTotal2.setGeometry(QtCore.QRect(690, 170, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(14)
        self.oppTotal2.setFont(font)
        self.oppTotal2.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #7d7a7a, \n"
"            stop:1 #c7bfbf);\n"
"            color: black;\n"
"}")
        self.oppTotal2.setObjectName("oppTotal2")
        self.oppTotal1 = QtWidgets.QLabel(parent=PokerScreen)
        self.oppTotal1.setGeometry(QtCore.QRect(360, 110, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(14)
        self.oppTotal1.setFont(font)
        self.oppTotal1.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #7d7a7a, \n"
"            stop:1 #c7bfbf);\n"
"            color: black;\n"
"}")
        self.oppTotal1.setObjectName("oppTotal1")
        self.rulesButton = QtWidgets.QPushButton(parent=PokerScreen)
        self.rulesButton.setGeometry(QtCore.QRect(10, 420, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        self.rulesButton.setFont(font)
        self.rulesButton.setObjectName("rulesButton")
        self.river.raise_()
        self.turn.raise_()
        self.flop3.raise_()
        self.flop2.raise_()
        self.flop1.raise_()
        self.graphicsView.raise_()
        self.playerHandLabel.raise_()
        self.totalLabel.raise_()
        self.leaveButton.raise_()
        self.opp3.raise_()
        self.opp2.raise_()
        self.opp1.raise_()
        self.dealButton.raise_()
        self.deckLabel.raise_()
        self.checkcallButton.raise_()
        self.betraiseButton.raise_()
        self.foldButton.raise_()
        self.potLabel.raise_()
        self.oppCount.raise_()
        self.label.raise_()
        self.allinButton.raise_()
        self.oppTotal3.raise_()
        self.oppTotal2.raise_()
        self.oppTotal1.raise_()
        self.rulesButton.raise_()

        self.retranslateUi(PokerScreen)
        QtCore.QMetaObject.connectSlotsByName(PokerScreen)

    def retranslateUi(self, PokerScreen):
        _translate = QtCore.QCoreApplication.translate
        PokerScreen.setWindowTitle(_translate("PokerScreen", "Form"))
        self.playerHandLabel.setText(_translate("PokerScreen", "Player Hand"))
        self.totalLabel.setText(_translate("PokerScreen", "Chip Total: "))
        self.leaveButton.setText(_translate("PokerScreen", "Leave"))
        self.dealButton.setText(_translate("PokerScreen", "Deal!"))
        self.checkcallButton.setText(_translate("PokerScreen", "Check"))
        self.betraiseButton.setText(_translate("PokerScreen", "Bet"))
        self.foldButton.setText(_translate("PokerScreen", "Fold"))
        self.potLabel.setText(_translate("PokerScreen", "Pot:"))
        self.label.setText(_translate("PokerScreen", "Opponents:"))
        self.allinButton.setText(_translate("PokerScreen", "ALL IN!!!"))
        self.oppTotal3.setText(_translate("PokerScreen", "Chips:"))
        self.oppTotal2.setText(_translate("PokerScreen", "Chips:"))
        self.oppTotal1.setText(_translate("PokerScreen", "Chips:"))
        self.rulesButton.setText(_translate("PokerScreen", "Rules"))
