# Form implementation generated from reading ui file 'poker.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PokerScreen(object):
    def setupUi(self, PokerScreen):
        PokerScreen.setObjectName("PokerScreen")
        PokerScreen.resize(800, 600)
        PokerScreen.setMinimumSize(QtCore.QSize(800, 600))
        PokerScreen.setMaximumSize(QtCore.QSize(800, 600))
        PokerScreen.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        PokerScreen.setStyleSheet("background-color: qlineargradient(\n"
"    x1:0, y1:0, x2:0, y2:1,\n"
"    stop:0 #009f00,\n"
"    stop:1 #004d00\n"
");")
        self.playerHandLabel = QtWidgets.QLabel(parent=PokerScreen)
        self.playerHandLabel.setGeometry(QtCore.QRect(320, 520, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(36)
        self.playerHandLabel.setFont(font)
        self.playerHandLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.playerHandLabel.setObjectName("playerHandLabel")
        self.totalLabel = QtWidgets.QLabel(parent=PokerScreen)
        self.totalLabel.setGeometry(QtCore.QRect(10, 480, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(24)
        self.totalLabel.setFont(font)
        self.totalLabel.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #7d7a7a, \n"
"            stop:1 #c7bfbf);\n"
"            color: black;\n"
"}")
        self.totalLabel.setObjectName("totalLabel")
        self.leaveButton = QtWidgets.QPushButton(parent=PokerScreen)
        self.leaveButton.setGeometry(QtCore.QRect(10, 540, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(20)
        self.leaveButton.setFont(font)
        self.leaveButton.setStyleSheet("QPushButton {background-color: qlineargradient(\n"
"            x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #ff0000,\n"
"            stop:1 #7d0000\n"
"    );\n"
"}")
        self.leaveButton.setObjectName("leaveButton")
        self.opp1 = QtWidgets.QLabel(parent=PokerScreen)
        self.opp1.setGeometry(QtCore.QRect(20, 220, 91, 91))
        self.opp1.setText("")
        self.opp1.setPixmap(QtGui.QPixmap("../assets/glass_joe.png"))
        self.opp1.setScaledContents(True)
        self.opp1.setObjectName("opp1")
        self.opp3 = QtWidgets.QLabel(parent=PokerScreen)
        self.opp3.setGeometry(QtCore.QRect(690, 220, 91, 91))
        self.opp3.setText("")
        self.opp3.setPixmap(QtGui.QPixmap("../assets/king_hippo.png"))
        self.opp3.setScaledContents(True)
        self.opp3.setObjectName("opp3")
        self.opp2 = QtWidgets.QLabel(parent=PokerScreen)
        self.opp2.setGeometry(QtCore.QRect(360, 10, 91, 91))
        self.opp2.setText("")
        self.opp2.setPixmap(QtGui.QPixmap("../assets/super_macho_man.png"))
        self.opp2.setScaledContents(True)
        self.opp2.setObjectName("opp2")
        self.flop1 = QtWidgets.QLabel(parent=PokerScreen)
        self.flop1.setGeometry(QtCore.QRect(190, 210, 71, 111))
        self.flop1.setText("")
        self.flop1.setObjectName("flop1")
        self.flop2 = QtWidgets.QLabel(parent=PokerScreen)
        self.flop2.setGeometry(QtCore.QRect(280, 210, 71, 111))
        self.flop2.setText("")
        self.flop2.setObjectName("flop2")
        self.flop3 = QtWidgets.QLabel(parent=PokerScreen)
        self.flop3.setGeometry(QtCore.QRect(370, 210, 71, 111))
        self.flop3.setText("")
        self.flop3.setObjectName("flop3")
        self.turn = QtWidgets.QLabel(parent=PokerScreen)
        self.turn.setGeometry(QtCore.QRect(460, 210, 71, 111))
        self.turn.setText("")
        self.turn.setObjectName("turn")
        self.river = QtWidgets.QLabel(parent=PokerScreen)
        self.river.setGeometry(QtCore.QRect(550, 210, 71, 111))
        self.river.setText("")
        self.river.setObjectName("river")

        self.retranslateUi(PokerScreen)
        QtCore.QMetaObject.connectSlotsByName(PokerScreen)

    def retranslateUi(self, PokerScreen):
        _translate = QtCore.QCoreApplication.translate
        PokerScreen.setWindowTitle(_translate("PokerScreen", "Form"))
        self.playerHandLabel.setText(_translate("PokerScreen", "Player Hand"))
        self.totalLabel.setText(_translate("PokerScreen", "Chip Total: "))
        self.leaveButton.setText(_translate("PokerScreen", "Leave"))
