# Form implementation generated from reading ui file 'roulette.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RouletteScreen(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: #0f6d39;")
        self.tableLabel = QtWidgets.QLabel(parent=Form)
        self.tableLabel.setGeometry(QtCore.QRect(-70, -90, 941, 511))
        self.tableLabel.setStyleSheet("QPushButton {\n"
"        background-color: qlineargradient(\n"
"            x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #7d7a7a, \n"
"        stop:1 #c7bfbf);\n"
"        color: black;\n"
"}")
        self.tableLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tableLabel.setText("")
        self.tableLabel.setPixmap(QtGui.QPixmap("../assets/table.jpg"))
        self.tableLabel.setScaledContents(True)
        self.tableLabel.setObjectName("tableLabel")
        self.wheelLabel = QtWidgets.QLabel(parent=Form)
        self.wheelLabel.setGeometry(QtCore.QRect(570, 370, 501, 511))
        self.wheelLabel.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.wheelLabel.setText("")
        self.wheelLabel.setPixmap(QtGui.QPixmap("../assets/wheel.png"))
        self.wheelLabel.setScaledContents(True)
        self.wheelLabel.setObjectName("wheelLabel")
        self.totalLabel = QtWidgets.QLabel(parent=Form)
        self.totalLabel.setGeometry(QtCore.QRect(10, 480, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(20)
        self.totalLabel.setFont(font)
        self.totalLabel.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #7d7a7a, \n"
"            stop:1 #c7bfbf);\n"
"            color: black;\n"
"}")
        self.totalLabel.setObjectName("totalLabel")
        self.theDirtySolution = QtWidgets.QLabel(parent=Form)
        self.theDirtySolution.setGeometry(QtCore.QRect(0, 400, 791, 231))
        self.theDirtySolution.setText("")
        self.theDirtySolution.setObjectName("theDirtySolution")
        self.r_1 = QtWidgets.QPushButton(parent=Form)
        self.r_1.setGeometry(QtCore.QRect(80, 10, 21, 20))
        self.r_1.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_1.setText("")
        self.r_1.setObjectName("r_1")
        self.r_2 = QtWidgets.QPushButton(parent=Form)
        self.r_2.setGeometry(QtCore.QRect(135, 10, 21, 20))
        self.r_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_2.setText("")
        self.r_2.setObjectName("r_2")
        self.r_3 = QtWidgets.QPushButton(parent=Form)
        self.r_3.setGeometry(QtCore.QRect(191, 10, 21, 20))
        self.r_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_3.setText("")
        self.r_3.setObjectName("r_3")
        self.r_4 = QtWidgets.QPushButton(parent=Form)
        self.r_4.setGeometry(QtCore.QRect(249, 10, 21, 20))
        self.r_4.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_4.setText("")
        self.r_4.setObjectName("r_4")
        self.r_5 = QtWidgets.QPushButton(parent=Form)
        self.r_5.setGeometry(QtCore.QRect(306, 10, 21, 20))
        self.r_5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_5.setText("")
        self.r_5.setObjectName("r_5")
        self.r_6 = QtWidgets.QPushButton(parent=Form)
        self.r_6.setGeometry(QtCore.QRect(363, 10, 21, 20))
        self.r_6.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_6.setText("")
        self.r_6.setObjectName("r_6")
        self.r_7 = QtWidgets.QPushButton(parent=Form)
        self.r_7.setGeometry(QtCore.QRect(419, 10, 21, 20))
        self.r_7.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_7.setText("")
        self.r_7.setObjectName("r_7")
        self.r_8 = QtWidgets.QPushButton(parent=Form)
        self.r_8.setGeometry(QtCore.QRect(475, 10, 21, 20))
        self.r_8.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_8.setText("")
        self.r_8.setObjectName("r_8")
        self.r_9 = QtWidgets.QPushButton(parent=Form)
        self.r_9.setGeometry(QtCore.QRect(532, 10, 21, 20))
        self.r_9.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_9.setText("")
        self.r_9.setObjectName("r_9")
        self.r_10 = QtWidgets.QPushButton(parent=Form)
        self.r_10.setGeometry(QtCore.QRect(589, 10, 21, 20))
        self.r_10.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_10.setText("")
        self.r_10.setObjectName("r_10")
        self.r_11 = QtWidgets.QPushButton(parent=Form)
        self.r_11.setGeometry(QtCore.QRect(645, 10, 21, 20))
        self.r_11.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_11.setText("")
        self.r_11.setObjectName("r_11")
        self.r_12 = QtWidgets.QPushButton(parent=Form)
        self.r_12.setGeometry(QtCore.QRect(702, 10, 21, 20))
        self.r_12.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.r_12.setText("")
        self.r_12.setObjectName("r_12")
        self.rp_1_2 = QtWidgets.QPushButton(parent=Form)
        self.rp_1_2.setGeometry(QtCore.QRect(107, 10, 21, 20))
        self.rp_1_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_1_2.setText("")
        self.rp_1_2.setObjectName("rp_1_2")
        self.rp_2_3 = QtWidgets.QPushButton(parent=Form)
        self.rp_2_3.setGeometry(QtCore.QRect(164, 10, 21, 20))
        self.rp_2_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_2_3.setText("")
        self.rp_2_3.setObjectName("rp_2_3")
        self.rp_3_4 = QtWidgets.QPushButton(parent=Form)
        self.rp_3_4.setGeometry(QtCore.QRect(220, 10, 21, 20))
        self.rp_3_4.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_3_4.setText("")
        self.rp_3_4.setObjectName("rp_3_4")
        self.rp_4_5 = QtWidgets.QPushButton(parent=Form)
        self.rp_4_5.setGeometry(QtCore.QRect(277, 10, 21, 20))
        self.rp_4_5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_4_5.setText("")
        self.rp_4_5.setObjectName("rp_4_5")
        self.rp_5_6 = QtWidgets.QPushButton(parent=Form)
        self.rp_5_6.setGeometry(QtCore.QRect(333, 10, 21, 20))
        self.rp_5_6.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_5_6.setText("")
        self.rp_5_6.setObjectName("rp_5_6")
        self.rp_6_7 = QtWidgets.QPushButton(parent=Form)
        self.rp_6_7.setGeometry(QtCore.QRect(390, 10, 21, 20))
        self.rp_6_7.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_6_7.setText("")
        self.rp_6_7.setObjectName("rp_6_7")
        self.rp_7_8 = QtWidgets.QPushButton(parent=Form)
        self.rp_7_8.setGeometry(QtCore.QRect(447, 10, 21, 20))
        self.rp_7_8.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_7_8.setText("")
        self.rp_7_8.setObjectName("rp_7_8")
        self.rp_8_9 = QtWidgets.QPushButton(parent=Form)
        self.rp_8_9.setGeometry(QtCore.QRect(503, 10, 21, 20))
        self.rp_8_9.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_8_9.setText("")
        self.rp_8_9.setObjectName("rp_8_9")
        self.rp_9_10 = QtWidgets.QPushButton(parent=Form)
        self.rp_9_10.setGeometry(QtCore.QRect(560, 10, 21, 20))
        self.rp_9_10.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_9_10.setText("")
        self.rp_9_10.setObjectName("rp_9_10")
        self.rp_10_11 = QtWidgets.QPushButton(parent=Form)
        self.rp_10_11.setGeometry(QtCore.QRect(617, 10, 21, 20))
        self.rp_10_11.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_10_11.setText("")
        self.rp_10_11.setObjectName("rp_10_11")
        self.rp_11_12 = QtWidgets.QPushButton(parent=Form)
        self.rp_11_12.setGeometry(QtCore.QRect(674, 10, 21, 20))
        self.rp_11_12.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.rp_11_12.setText("")
        self.rp_11_12.setObjectName("rp_11_12")
        self.spinButton = QtWidgets.QPushButton(parent=Form)
        self.spinButton.setGeometry(QtCore.QRect(280, 340, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Broadway Flat 3D Filled")
        font.setPointSize(50)
        self.spinButton.setFont(font)
        self.spinButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"    x1:0, y1:0, x2:0, y2:1,\n"
"    stop:0 rgba(255, 0, 0, 255), stop:1 rgba(80, 0, 0, 255));\n"
"    color: white;\n"
"}")
        self.spinButton.setObjectName("spinButton")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(570, 380, 61, 41))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../assets/pointer.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView.setGeometry(QtCore.QRect(510, 330, 301, 281))
        self.graphicsView.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.graphicsView.setObjectName("graphicsView")
        self.p_1_2 = QtWidgets.QPushButton(parent=Form)
        self.p_1_2.setGeometry(QtCore.QRect(80, 138, 21, 20))
        self.p_1_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_1_2.setText("")
        self.p_1_2.setObjectName("p_1_2")
        self.p_2_3 = QtWidgets.QPushButton(parent=Form)
        self.p_2_3.setGeometry(QtCore.QRect(80, 72, 21, 20))
        self.p_2_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_2_3.setText("")
        self.p_2_3.setObjectName("p_2_3")
        self.p_4_5 = QtWidgets.QPushButton(parent=Form)
        self.p_4_5.setGeometry(QtCore.QRect(135, 138, 21, 20))
        self.p_4_5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_4_5.setText("")
        self.p_4_5.setObjectName("p_4_5")
        self.p_5_6 = QtWidgets.QPushButton(parent=Form)
        self.p_5_6.setGeometry(QtCore.QRect(135, 72, 21, 20))
        self.p_5_6.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_5_6.setText("")
        self.p_5_6.setObjectName("p_5_6")
        self.p_7_8 = QtWidgets.QPushButton(parent=Form)
        self.p_7_8.setGeometry(QtCore.QRect(191, 138, 21, 20))
        self.p_7_8.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_7_8.setText("")
        self.p_7_8.setObjectName("p_7_8")
        self.p_8_9 = QtWidgets.QPushButton(parent=Form)
        self.p_8_9.setGeometry(QtCore.QRect(191, 72, 21, 20))
        self.p_8_9.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_8_9.setText("")
        self.p_8_9.setObjectName("p_8_9")
        self.p_10_11 = QtWidgets.QPushButton(parent=Form)
        self.p_10_11.setGeometry(QtCore.QRect(249, 138, 21, 20))
        self.p_10_11.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_10_11.setText("")
        self.p_10_11.setObjectName("p_10_11")
        self.p_13_14 = QtWidgets.QPushButton(parent=Form)
        self.p_13_14.setGeometry(QtCore.QRect(306, 138, 21, 20))
        self.p_13_14.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_13_14.setText("")
        self.p_13_14.setObjectName("p_13_14")
        self.p_11_12 = QtWidgets.QPushButton(parent=Form)
        self.p_11_12.setGeometry(QtCore.QRect(249, 72, 21, 20))
        self.p_11_12.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_11_12.setText("")
        self.p_11_12.setObjectName("p_11_12")
        self.p_14_15 = QtWidgets.QPushButton(parent=Form)
        self.p_14_15.setGeometry(QtCore.QRect(306, 72, 21, 20))
        self.p_14_15.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_14_15.setText("")
        self.p_14_15.setObjectName("p_14_15")
        self.p_16_17 = QtWidgets.QPushButton(parent=Form)
        self.p_16_17.setGeometry(QtCore.QRect(363, 138, 21, 20))
        self.p_16_17.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_16_17.setText("")
        self.p_16_17.setObjectName("p_16_17")
        self.p_17_18 = QtWidgets.QPushButton(parent=Form)
        self.p_17_18.setGeometry(QtCore.QRect(363, 72, 21, 20))
        self.p_17_18.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_17_18.setText("")
        self.p_17_18.setObjectName("p_17_18")
        self.p_19_20 = QtWidgets.QPushButton(parent=Form)
        self.p_19_20.setGeometry(QtCore.QRect(419, 138, 21, 20))
        self.p_19_20.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_19_20.setText("")
        self.p_19_20.setObjectName("p_19_20")
        self.p_20_21 = QtWidgets.QPushButton(parent=Form)
        self.p_20_21.setGeometry(QtCore.QRect(419, 72, 21, 20))
        self.p_20_21.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_20_21.setText("")
        self.p_20_21.setObjectName("p_20_21")
        self.p_22_23 = QtWidgets.QPushButton(parent=Form)
        self.p_22_23.setGeometry(QtCore.QRect(475, 138, 21, 20))
        self.p_22_23.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_22_23.setText("")
        self.p_22_23.setObjectName("p_22_23")
        self.p_23_24 = QtWidgets.QPushButton(parent=Form)
        self.p_23_24.setGeometry(QtCore.QRect(475, 72, 21, 20))
        self.p_23_24.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_23_24.setText("")
        self.p_23_24.setObjectName("p_23_24")
        self.p_25_26 = QtWidgets.QPushButton(parent=Form)
        self.p_25_26.setGeometry(QtCore.QRect(532, 138, 21, 20))
        self.p_25_26.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_25_26.setText("")
        self.p_25_26.setObjectName("p_25_26")
        self.p_26_27 = QtWidgets.QPushButton(parent=Form)
        self.p_26_27.setGeometry(QtCore.QRect(532, 72, 21, 20))
        self.p_26_27.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_26_27.setText("")
        self.p_26_27.setObjectName("p_26_27")
        self.p_28_29 = QtWidgets.QPushButton(parent=Form)
        self.p_28_29.setGeometry(QtCore.QRect(589, 138, 21, 20))
        self.p_28_29.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_28_29.setText("")
        self.p_28_29.setObjectName("p_28_29")
        self.p_29_30 = QtWidgets.QPushButton(parent=Form)
        self.p_29_30.setGeometry(QtCore.QRect(589, 72, 21, 20))
        self.p_29_30.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_29_30.setText("")
        self.p_29_30.setObjectName("p_29_30")
        self.p_31_32 = QtWidgets.QPushButton(parent=Form)
        self.p_31_32.setGeometry(QtCore.QRect(645, 138, 21, 20))
        self.p_31_32.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_31_32.setText("")
        self.p_31_32.setObjectName("p_31_32")
        self.p_32_33 = QtWidgets.QPushButton(parent=Form)
        self.p_32_33.setGeometry(QtCore.QRect(645, 72, 21, 20))
        self.p_32_33.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_32_33.setText("")
        self.p_32_33.setObjectName("p_32_33")
        self.p_34_35 = QtWidgets.QPushButton(parent=Form)
        self.p_34_35.setGeometry(QtCore.QRect(702, 139, 21, 20))
        self.p_34_35.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_34_35.setText("")
        self.p_34_35.setObjectName("p_34_35")
        self.p_35_36 = QtWidgets.QPushButton(parent=Form)
        self.p_35_36.setGeometry(QtCore.QRect(702, 72, 21, 20))
        self.p_35_36.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_35_36.setText("")
        self.p_35_36.setObjectName("p_35_36")
        self.p_1_4 = QtWidgets.QPushButton(parent=Form)
        self.p_1_4.setGeometry(QtCore.QRect(107, 171, 21, 20))
        self.p_1_4.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_1_4.setText("")
        self.p_1_4.setObjectName("p_1_4")
        self.p_2_5 = QtWidgets.QPushButton(parent=Form)
        self.p_2_5.setGeometry(QtCore.QRect(107, 105, 21, 20))
        self.p_2_5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_2_5.setText("")
        self.p_2_5.setObjectName("p_2_5")
        self.p_3_6 = QtWidgets.QPushButton(parent=Form)
        self.p_3_6.setGeometry(QtCore.QRect(107, 38, 21, 20))
        self.p_3_6.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_3_6.setText("")
        self.p_3_6.setObjectName("p_3_6")
        self.p_4_7 = QtWidgets.QPushButton(parent=Form)
        self.p_4_7.setGeometry(QtCore.QRect(164, 171, 21, 20))
        self.p_4_7.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_4_7.setText("")
        self.p_4_7.setObjectName("p_4_7")
        self.p_5_8 = QtWidgets.QPushButton(parent=Form)
        self.p_5_8.setGeometry(QtCore.QRect(164, 105, 21, 20))
        self.p_5_8.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_5_8.setText("")
        self.p_5_8.setObjectName("p_5_8")
        self.p_6_9 = QtWidgets.QPushButton(parent=Form)
        self.p_6_9.setGeometry(QtCore.QRect(164, 38, 21, 20))
        self.p_6_9.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_6_9.setText("")
        self.p_6_9.setObjectName("p_6_9")
        self.p_7_10 = QtWidgets.QPushButton(parent=Form)
        self.p_7_10.setGeometry(QtCore.QRect(220, 171, 21, 20))
        self.p_7_10.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_7_10.setText("")
        self.p_7_10.setObjectName("p_7_10")
        self.p_8_11 = QtWidgets.QPushButton(parent=Form)
        self.p_8_11.setGeometry(QtCore.QRect(220, 105, 21, 20))
        self.p_8_11.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_8_11.setText("")
        self.p_8_11.setObjectName("p_8_11")
        self.p_9_12 = QtWidgets.QPushButton(parent=Form)
        self.p_9_12.setGeometry(QtCore.QRect(220, 38, 21, 20))
        self.p_9_12.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_9_12.setText("")
        self.p_9_12.setObjectName("p_9_12")
        self.p_10_13 = QtWidgets.QPushButton(parent=Form)
        self.p_10_13.setGeometry(QtCore.QRect(277, 171, 21, 20))
        self.p_10_13.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_10_13.setText("")
        self.p_10_13.setObjectName("p_10_13")
        self.p_11_14 = QtWidgets.QPushButton(parent=Form)
        self.p_11_14.setGeometry(QtCore.QRect(277, 105, 21, 20))
        self.p_11_14.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_11_14.setText("")
        self.p_11_14.setObjectName("p_11_14")
        self.p_12_15 = QtWidgets.QPushButton(parent=Form)
        self.p_12_15.setGeometry(QtCore.QRect(277, 38, 21, 20))
        self.p_12_15.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_12_15.setText("")
        self.p_12_15.setObjectName("p_12_15")
        self.p_13_16 = QtWidgets.QPushButton(parent=Form)
        self.p_13_16.setGeometry(QtCore.QRect(333, 171, 21, 20))
        self.p_13_16.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_13_16.setText("")
        self.p_13_16.setObjectName("p_13_16")
        self.p_14_17 = QtWidgets.QPushButton(parent=Form)
        self.p_14_17.setGeometry(QtCore.QRect(333, 105, 21, 20))
        self.p_14_17.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_14_17.setText("")
        self.p_14_17.setObjectName("p_14_17")
        self.p_15_18 = QtWidgets.QPushButton(parent=Form)
        self.p_15_18.setGeometry(QtCore.QRect(333, 38, 21, 20))
        self.p_15_18.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_15_18.setText("")
        self.p_15_18.setObjectName("p_15_18")
        self.p_16_19 = QtWidgets.QPushButton(parent=Form)
        self.p_16_19.setGeometry(QtCore.QRect(390, 171, 21, 20))
        self.p_16_19.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_16_19.setText("")
        self.p_16_19.setObjectName("p_16_19")
        self.p_17_20 = QtWidgets.QPushButton(parent=Form)
        self.p_17_20.setGeometry(QtCore.QRect(390, 105, 21, 20))
        self.p_17_20.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_17_20.setText("")
        self.p_17_20.setObjectName("p_17_20")
        self.p_18_21 = QtWidgets.QPushButton(parent=Form)
        self.p_18_21.setGeometry(QtCore.QRect(390, 38, 21, 20))
        self.p_18_21.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_18_21.setText("")
        self.p_18_21.setObjectName("p_18_21")
        self.p_19_22 = QtWidgets.QPushButton(parent=Form)
        self.p_19_22.setGeometry(QtCore.QRect(447, 171, 21, 20))
        self.p_19_22.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_19_22.setText("")
        self.p_19_22.setObjectName("p_19_22")
        self.p_20_23 = QtWidgets.QPushButton(parent=Form)
        self.p_20_23.setGeometry(QtCore.QRect(447, 105, 21, 20))
        self.p_20_23.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_20_23.setText("")
        self.p_20_23.setObjectName("p_20_23")
        self.p_21_24 = QtWidgets.QPushButton(parent=Form)
        self.p_21_24.setGeometry(QtCore.QRect(447, 38, 21, 20))
        self.p_21_24.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_21_24.setText("")
        self.p_21_24.setObjectName("p_21_24")
        self.p_22_25 = QtWidgets.QPushButton(parent=Form)
        self.p_22_25.setGeometry(QtCore.QRect(503, 171, 21, 20))
        self.p_22_25.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_22_25.setText("")
        self.p_22_25.setObjectName("p_22_25")
        self.p_23_26 = QtWidgets.QPushButton(parent=Form)
        self.p_23_26.setGeometry(QtCore.QRect(503, 105, 21, 20))
        self.p_23_26.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_23_26.setText("")
        self.p_23_26.setObjectName("p_23_26")
        self.p_24_27 = QtWidgets.QPushButton(parent=Form)
        self.p_24_27.setGeometry(QtCore.QRect(503, 38, 21, 20))
        self.p_24_27.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_24_27.setText("")
        self.p_24_27.setObjectName("p_24_27")
        self.p_25_28 = QtWidgets.QPushButton(parent=Form)
        self.p_25_28.setGeometry(QtCore.QRect(560, 171, 21, 20))
        self.p_25_28.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_25_28.setText("")
        self.p_25_28.setObjectName("p_25_28")
        self.p_26_29 = QtWidgets.QPushButton(parent=Form)
        self.p_26_29.setGeometry(QtCore.QRect(560, 105, 21, 20))
        self.p_26_29.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_26_29.setText("")
        self.p_26_29.setObjectName("p_26_29")
        self.p_27_30 = QtWidgets.QPushButton(parent=Form)
        self.p_27_30.setGeometry(QtCore.QRect(560, 38, 21, 20))
        self.p_27_30.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_27_30.setText("")
        self.p_27_30.setObjectName("p_27_30")
        self.p_28_31 = QtWidgets.QPushButton(parent=Form)
        self.p_28_31.setGeometry(QtCore.QRect(617, 171, 21, 20))
        self.p_28_31.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_28_31.setText("")
        self.p_28_31.setObjectName("p_28_31")
        self.p_29_32 = QtWidgets.QPushButton(parent=Form)
        self.p_29_32.setGeometry(QtCore.QRect(617, 105, 21, 20))
        self.p_29_32.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_29_32.setText("")
        self.p_29_32.setObjectName("p_29_32")
        self.p_30_33 = QtWidgets.QPushButton(parent=Form)
        self.p_30_33.setGeometry(QtCore.QRect(617, 38, 21, 20))
        self.p_30_33.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_30_33.setText("")
        self.p_30_33.setObjectName("p_30_33")
        self.p_31_34 = QtWidgets.QPushButton(parent=Form)
        self.p_31_34.setGeometry(QtCore.QRect(674, 171, 21, 20))
        self.p_31_34.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_31_34.setText("")
        self.p_31_34.setObjectName("p_31_34")
        self.p_32_35 = QtWidgets.QPushButton(parent=Form)
        self.p_32_35.setGeometry(QtCore.QRect(674, 105, 21, 20))
        self.p_32_35.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_32_35.setText("")
        self.p_32_35.setObjectName("p_32_35")
        self.p_33_36 = QtWidgets.QPushButton(parent=Form)
        self.p_33_36.setGeometry(QtCore.QRect(674, 38, 21, 20))
        self.p_33_36.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.p_33_36.setText("")
        self.p_33_36.setObjectName("p_33_36")
        self.tw_1 = QtWidgets.QPushButton(parent=Form)
        self.tw_1.setGeometry(QtCore.QRect(62, 214, 224, 48))
        self.tw_1.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.tw_1.setText("")
        self.tw_1.setObjectName("tw_1")
        self.tr_0_1_2 = QtWidgets.QPushButton(parent=Form)
        self.tr_0_1_2.setGeometry(QtCore.QRect(50, 140, 21, 20))
        self.tr_0_1_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.tr_0_1_2.setText("")
        self.tr_0_1_2.setObjectName("tr_0_1_2")
        self.tr_0_2_3 = QtWidgets.QPushButton(parent=Form)
        self.tr_0_2_3.setGeometry(QtCore.QRect(50, 70, 21, 20))
        self.tr_0_2_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.tr_0_2_3.setText("")
        self.tr_0_2_3.setObjectName("tr_0_2_3")
        self.leaveButton = QtWidgets.QPushButton(parent=Form)
        self.leaveButton.setGeometry(QtCore.QRect(10, 560, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        self.leaveButton.setFont(font)
        self.leaveButton.setStyleSheet("QPushButton {background-color: qlineargradient(\n"
"            x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #ff0000,\n"
"            stop:1 #7d0000\n"
"    );\n"
"}")
        self.leaveButton.setObjectName("leaveButton")
        self.s_3 = QtWidgets.QPushButton(parent=Form)
        self.s_3.setGeometry(QtCore.QRect(60, 19, 55, 61))
        self.s_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_3.setText("")
        self.s_3.setObjectName("s_3")
        self.s_2 = QtWidgets.QPushButton(parent=Form)
        self.s_2.setGeometry(QtCore.QRect(60, 80, 55, 67))
        self.s_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_2.setText("")
        self.s_2.setObjectName("s_2")
        self.s_1 = QtWidgets.QPushButton(parent=Form)
        self.s_1.setGeometry(QtCore.QRect(60, 150, 55, 61))
        self.s_1.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_1.setText("")
        self.s_1.setObjectName("s_1")
        self.s_4 = QtWidgets.QPushButton(parent=Form)
        self.s_4.setGeometry(QtCore.QRect(120, 150, 55, 61))
        self.s_4.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_4.setText("")
        self.s_4.setObjectName("s_4")
        self.s_6 = QtWidgets.QPushButton(parent=Form)
        self.s_6.setGeometry(QtCore.QRect(120, 20, 55, 61))
        self.s_6.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_6.setText("")
        self.s_6.setObjectName("s_6")
        self.s_7 = QtWidgets.QPushButton(parent=Form)
        self.s_7.setGeometry(QtCore.QRect(174, 150, 55, 61))
        self.s_7.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_7.setText("")
        self.s_7.setObjectName("s_7")
        self.s_9 = QtWidgets.QPushButton(parent=Form)
        self.s_9.setGeometry(QtCore.QRect(174, 20, 55, 61))
        self.s_9.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_9.setText("")
        self.s_9.setObjectName("s_9")
        self.s_12 = QtWidgets.QPushButton(parent=Form)
        self.s_12.setGeometry(QtCore.QRect(230, 20, 55, 61))
        self.s_12.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_12.setText("")
        self.s_12.setObjectName("s_12")
        self.s_10 = QtWidgets.QPushButton(parent=Form)
        self.s_10.setGeometry(QtCore.QRect(230, 150, 55, 61))
        self.s_10.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_10.setText("")
        self.s_10.setObjectName("s_10")
        self.s_13 = QtWidgets.QPushButton(parent=Form)
        self.s_13.setGeometry(QtCore.QRect(290, 150, 55, 61))
        self.s_13.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_13.setText("")
        self.s_13.setObjectName("s_13")
        self.s_15 = QtWidgets.QPushButton(parent=Form)
        self.s_15.setGeometry(QtCore.QRect(290, 20, 55, 61))
        self.s_15.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_15.setText("")
        self.s_15.setObjectName("s_15")
        self.s_16 = QtWidgets.QPushButton(parent=Form)
        self.s_16.setGeometry(QtCore.QRect(344, 150, 55, 61))
        self.s_16.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_16.setText("")
        self.s_16.setObjectName("s_16")
        self.s_18 = QtWidgets.QPushButton(parent=Form)
        self.s_18.setGeometry(QtCore.QRect(344, 20, 55, 61))
        self.s_18.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_18.setText("")
        self.s_18.setObjectName("s_18")
        self.s_19 = QtWidgets.QPushButton(parent=Form)
        self.s_19.setGeometry(QtCore.QRect(400, 150, 55, 61))
        self.s_19.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_19.setText("")
        self.s_19.setObjectName("s_19")
        self.s_21 = QtWidgets.QPushButton(parent=Form)
        self.s_21.setGeometry(QtCore.QRect(400, 20, 55, 61))
        self.s_21.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_21.setText("")
        self.s_21.setObjectName("s_21")
        self.s_22 = QtWidgets.QPushButton(parent=Form)
        self.s_22.setGeometry(QtCore.QRect(460, 150, 55, 61))
        self.s_22.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_22.setText("")
        self.s_22.setObjectName("s_22")
        self.s_24 = QtWidgets.QPushButton(parent=Form)
        self.s_24.setGeometry(QtCore.QRect(460, 20, 55, 61))
        self.s_24.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_24.setText("")
        self.s_24.setObjectName("s_24")
        self.s_25 = QtWidgets.QPushButton(parent=Form)
        self.s_25.setGeometry(QtCore.QRect(514, 150, 55, 61))
        self.s_25.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_25.setText("")
        self.s_25.setObjectName("s_25")
        self.s_27 = QtWidgets.QPushButton(parent=Form)
        self.s_27.setGeometry(QtCore.QRect(514, 20, 55, 61))
        self.s_27.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_27.setText("")
        self.s_27.setObjectName("s_27")
        self.s_28 = QtWidgets.QPushButton(parent=Form)
        self.s_28.setGeometry(QtCore.QRect(570, 150, 55, 61))
        self.s_28.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_28.setText("")
        self.s_28.setObjectName("s_28")
        self.s_30 = QtWidgets.QPushButton(parent=Form)
        self.s_30.setGeometry(QtCore.QRect(570, 20, 55, 61))
        self.s_30.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_30.setText("")
        self.s_30.setObjectName("s_30")
        self.s_31 = QtWidgets.QPushButton(parent=Form)
        self.s_31.setGeometry(QtCore.QRect(630, 150, 55, 61))
        self.s_31.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_31.setText("")
        self.s_31.setObjectName("s_31")
        self.s_33 = QtWidgets.QPushButton(parent=Form)
        self.s_33.setGeometry(QtCore.QRect(630, 20, 55, 61))
        self.s_33.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_33.setText("")
        self.s_33.setObjectName("s_33")
        self.s_34 = QtWidgets.QPushButton(parent=Form)
        self.s_34.setGeometry(QtCore.QRect(684, 150, 55, 61))
        self.s_34.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_34.setText("")
        self.s_34.setObjectName("s_34")
        self.s_36 = QtWidgets.QPushButton(parent=Form)
        self.s_36.setGeometry(QtCore.QRect(684, 20, 55, 61))
        self.s_36.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_36.setText("")
        self.s_36.setObjectName("s_36")
        self.s_5 = QtWidgets.QPushButton(parent=Form)
        self.s_5.setGeometry(QtCore.QRect(120, 80, 55, 67))
        self.s_5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_5.setText("")
        self.s_5.setObjectName("s_5")
        self.s_8 = QtWidgets.QPushButton(parent=Form)
        self.s_8.setGeometry(QtCore.QRect(174, 80, 55, 67))
        self.s_8.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_8.setText("")
        self.s_8.setObjectName("s_8")
        self.s_11 = QtWidgets.QPushButton(parent=Form)
        self.s_11.setGeometry(QtCore.QRect(230, 80, 55, 67))
        self.s_11.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_11.setText("")
        self.s_11.setObjectName("s_11")
        self.s_14 = QtWidgets.QPushButton(parent=Form)
        self.s_14.setGeometry(QtCore.QRect(290, 80, 55, 67))
        self.s_14.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_14.setText("")
        self.s_14.setObjectName("s_14")
        self.s_17 = QtWidgets.QPushButton(parent=Form)
        self.s_17.setGeometry(QtCore.QRect(344, 80, 55, 67))
        self.s_17.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_17.setText("")
        self.s_17.setObjectName("s_17")
        self.s_20 = QtWidgets.QPushButton(parent=Form)
        self.s_20.setGeometry(QtCore.QRect(400, 80, 55, 67))
        self.s_20.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_20.setText("")
        self.s_20.setObjectName("s_20")
        self.s_23 = QtWidgets.QPushButton(parent=Form)
        self.s_23.setGeometry(QtCore.QRect(460, 80, 55, 67))
        self.s_23.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_23.setText("")
        self.s_23.setObjectName("s_23")
        self.s_26 = QtWidgets.QPushButton(parent=Form)
        self.s_26.setGeometry(QtCore.QRect(514, 80, 55, 67))
        self.s_26.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_26.setText("")
        self.s_26.setObjectName("s_26")
        self.s_29 = QtWidgets.QPushButton(parent=Form)
        self.s_29.setGeometry(QtCore.QRect(570, 80, 55, 67))
        self.s_29.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_29.setText("")
        self.s_29.setObjectName("s_29")
        self.s_32 = QtWidgets.QPushButton(parent=Form)
        self.s_32.setGeometry(QtCore.QRect(630, 80, 55, 67))
        self.s_32.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_32.setText("")
        self.s_32.setObjectName("s_32")
        self.s_35 = QtWidgets.QPushButton(parent=Form)
        self.s_35.setGeometry(QtCore.QRect(684, 80, 55, 67))
        self.s_35.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_35.setText("")
        self.s_35.setObjectName("s_35")
        self.s_0 = QtWidgets.QPushButton(parent=Form)
        self.s_0.setGeometry(QtCore.QRect(7, 20, 52, 191))
        self.s_0.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.s_0.setText("")
        self.s_0.setObjectName("s_0")
        self.q_1_2_4_5 = QtWidgets.QPushButton(parent=Form)
        self.q_1_2_4_5.setGeometry(QtCore.QRect(107, 138, 21, 20))
        self.q_1_2_4_5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_1_2_4_5.setText("")
        self.q_1_2_4_5.setObjectName("q_1_2_4_5")
        self.q_2_3_5_6 = QtWidgets.QPushButton(parent=Form)
        self.q_2_3_5_6.setGeometry(QtCore.QRect(107, 72, 21, 20))
        self.q_2_3_5_6.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_2_3_5_6.setText("")
        self.q_2_3_5_6.setObjectName("q_2_3_5_6")
        self.q_4_5_7_8 = QtWidgets.QPushButton(parent=Form)
        self.q_4_5_7_8.setGeometry(QtCore.QRect(163, 138, 21, 20))
        self.q_4_5_7_8.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_4_5_7_8.setText("")
        self.q_4_5_7_8.setObjectName("q_4_5_7_8")
        self.q_5_6_8_9 = QtWidgets.QPushButton(parent=Form)
        self.q_5_6_8_9.setGeometry(QtCore.QRect(163, 72, 21, 20))
        self.q_5_6_8_9.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_5_6_8_9.setText("")
        self.q_5_6_8_9.setObjectName("q_5_6_8_9")
        self.q_8_9_11_12 = QtWidgets.QPushButton(parent=Form)
        self.q_8_9_11_12.setGeometry(QtCore.QRect(220, 72, 21, 20))
        self.q_8_9_11_12.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_8_9_11_12.setText("")
        self.q_8_9_11_12.setObjectName("q_8_9_11_12")
        self.q_7_8_10_11 = QtWidgets.QPushButton(parent=Form)
        self.q_7_8_10_11.setGeometry(QtCore.QRect(220, 138, 21, 20))
        self.q_7_8_10_11.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_7_8_10_11.setText("")
        self.q_7_8_10_11.setObjectName("q_7_8_10_11")
        self.q_13_14_16_17 = QtWidgets.QPushButton(parent=Form)
        self.q_13_14_16_17.setGeometry(QtCore.QRect(334, 138, 21, 20))
        self.q_13_14_16_17.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_13_14_16_17.setText("")
        self.q_13_14_16_17.setObjectName("q_13_14_16_17")
        self.q_14_15_17_18 = QtWidgets.QPushButton(parent=Form)
        self.q_14_15_17_18.setGeometry(QtCore.QRect(334, 72, 21, 20))
        self.q_14_15_17_18.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_14_15_17_18.setText("")
        self.q_14_15_17_18.setObjectName("q_14_15_17_18")
        self.q_10_11_13_14 = QtWidgets.QPushButton(parent=Form)
        self.q_10_11_13_14.setGeometry(QtCore.QRect(276, 138, 21, 20))
        self.q_10_11_13_14.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_10_11_13_14.setText("")
        self.q_10_11_13_14.setObjectName("q_10_11_13_14")
        self.q_11_12_14_15 = QtWidgets.QPushButton(parent=Form)
        self.q_11_12_14_15.setGeometry(QtCore.QRect(276, 72, 21, 20))
        self.q_11_12_14_15.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_11_12_14_15.setText("")
        self.q_11_12_14_15.setObjectName("q_11_12_14_15")
        self.q_17_18_20_21 = QtWidgets.QPushButton(parent=Form)
        self.q_17_18_20_21.setGeometry(QtCore.QRect(390, 72, 21, 20))
        self.q_17_18_20_21.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_17_18_20_21.setText("")
        self.q_17_18_20_21.setObjectName("q_17_18_20_21")
        self.q_16_17_19_20 = QtWidgets.QPushButton(parent=Form)
        self.q_16_17_19_20.setGeometry(QtCore.QRect(390, 138, 21, 20))
        self.q_16_17_19_20.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_16_17_19_20.setText("")
        self.q_16_17_19_20.setObjectName("q_16_17_19_20")
        self.q_19_20_22_23 = QtWidgets.QPushButton(parent=Form)
        self.q_19_20_22_23.setGeometry(QtCore.QRect(447, 138, 21, 20))
        self.q_19_20_22_23.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_19_20_22_23.setText("")
        self.q_19_20_22_23.setObjectName("q_19_20_22_23")
        self.q_20_21_23_24 = QtWidgets.QPushButton(parent=Form)
        self.q_20_21_23_24.setGeometry(QtCore.QRect(447, 72, 21, 20))
        self.q_20_21_23_24.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_20_21_23_24.setText("")
        self.q_20_21_23_24.setObjectName("q_20_21_23_24")
        self.q_22_23_25_26 = QtWidgets.QPushButton(parent=Form)
        self.q_22_23_25_26.setGeometry(QtCore.QRect(503, 138, 21, 20))
        self.q_22_23_25_26.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_22_23_25_26.setText("")
        self.q_22_23_25_26.setObjectName("q_22_23_25_26")
        self.q_23_24_26_27 = QtWidgets.QPushButton(parent=Form)
        self.q_23_24_26_27.setGeometry(QtCore.QRect(503, 72, 21, 20))
        self.q_23_24_26_27.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_23_24_26_27.setText("")
        self.q_23_24_26_27.setObjectName("q_23_24_26_27")
        self.q_25_26_28_29 = QtWidgets.QPushButton(parent=Form)
        self.q_25_26_28_29.setGeometry(QtCore.QRect(560, 138, 21, 20))
        self.q_25_26_28_29.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_25_26_28_29.setText("")
        self.q_25_26_28_29.setObjectName("q_25_26_28_29")
        self.q_26_27_29_30 = QtWidgets.QPushButton(parent=Form)
        self.q_26_27_29_30.setGeometry(QtCore.QRect(560, 72, 21, 20))
        self.q_26_27_29_30.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_26_27_29_30.setText("")
        self.q_26_27_29_30.setObjectName("q_26_27_29_30")
        self.q_28_29_31_32 = QtWidgets.QPushButton(parent=Form)
        self.q_28_29_31_32.setGeometry(QtCore.QRect(617, 138, 21, 20))
        self.q_28_29_31_32.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_28_29_31_32.setText("")
        self.q_28_29_31_32.setObjectName("q_28_29_31_32")
        self.q_29_30_32_33 = QtWidgets.QPushButton(parent=Form)
        self.q_29_30_32_33.setGeometry(QtCore.QRect(617, 72, 21, 20))
        self.q_29_30_32_33.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_29_30_32_33.setText("")
        self.q_29_30_32_33.setObjectName("q_29_30_32_33")
        self.q_31_32_34_35 = QtWidgets.QPushButton(parent=Form)
        self.q_31_32_34_35.setGeometry(QtCore.QRect(674, 138, 21, 20))
        self.q_31_32_34_35.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_31_32_34_35.setText("")
        self.q_31_32_34_35.setObjectName("q_31_32_34_35")
        self.q_32_33_35_36 = QtWidgets.QPushButton(parent=Form)
        self.q_32_33_35_36.setGeometry(QtCore.QRect(674, 72, 21, 20))
        self.q_32_33_35_36.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.q_32_33_35_36.setText("")
        self.q_32_33_35_36.setObjectName("q_32_33_35_36")
        self.h_1 = QtWidgets.QPushButton(parent=Form)
        self.h_1.setGeometry(QtCore.QRect(60, 264, 113, 51))
        self.h_1.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.h_1.setText("")
        self.h_1.setObjectName("h_1")
        self.h_2 = QtWidgets.QPushButton(parent=Form)
        self.h_2.setGeometry(QtCore.QRect(628, 266, 111, 46))
        self.h_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.h_2.setText("")
        self.h_2.setObjectName("h_2")
        self.even = QtWidgets.QPushButton(parent=Form)
        self.even.setGeometry(QtCore.QRect(175, 265, 111, 48))
        self.even.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.even.setText("")
        self.even.setObjectName("even")
        self.odd = QtWidgets.QPushButton(parent=Form)
        self.odd.setGeometry(QtCore.QRect(515, 265, 111, 48))
        self.odd.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.odd.setText("")
        self.odd.setObjectName("odd")
        self.red = QtWidgets.QPushButton(parent=Form)
        self.red.setGeometry(QtCore.QRect(289, 265, 111, 48))
        self.red.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.red.setText("")
        self.red.setObjectName("red")
        self.black = QtWidgets.QPushButton(parent=Form)
        self.black.setGeometry(QtCore.QRect(402, 265, 111, 48))
        self.black.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.black.setText("")
        self.black.setObjectName("black")
        self.tw_2 = QtWidgets.QPushButton(parent=Form)
        self.tw_2.setGeometry(QtCore.QRect(289, 214, 224, 48))
        self.tw_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.tw_2.setText("")
        self.tw_2.setObjectName("tw_2")
        self.tw_3 = QtWidgets.QPushButton(parent=Form)
        self.tw_3.setGeometry(QtCore.QRect(516, 214, 224, 48))
        self.tw_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.tw_3.setText("")
        self.tw_3.setObjectName("tw_3")
        self.c_1 = QtWidgets.QPushButton(parent=Form)
        self.c_1.setGeometry(QtCore.QRect(742, 18, 54, 63))
        self.c_1.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.c_1.setText("")
        self.c_1.setObjectName("c_1")
        self.c_2 = QtWidgets.QPushButton(parent=Form)
        self.c_2.setGeometry(QtCore.QRect(742, 83, 54, 64))
        self.c_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.c_2.setText("")
        self.c_2.setObjectName("c_2")
        self.c_3 = QtWidgets.QPushButton(parent=Form)
        self.c_3.setGeometry(QtCore.QRect(742, 148, 54, 64))
        self.c_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.c_3.setText("")
        self.c_3.setObjectName("c_3")
        self.wheelLabel.raise_()
        self.theDirtySolution.raise_()
        self.tableLabel.raise_()
        self.totalLabel.raise_()
        self.r_1.raise_()
        self.r_2.raise_()
        self.r_3.raise_()
        self.r_4.raise_()
        self.r_5.raise_()
        self.r_6.raise_()
        self.r_7.raise_()
        self.r_8.raise_()
        self.r_9.raise_()
        self.r_10.raise_()
        self.r_11.raise_()
        self.r_12.raise_()
        self.rp_1_2.raise_()
        self.rp_2_3.raise_()
        self.rp_3_4.raise_()
        self.rp_4_5.raise_()
        self.rp_5_6.raise_()
        self.rp_6_7.raise_()
        self.rp_7_8.raise_()
        self.rp_8_9.raise_()
        self.rp_9_10.raise_()
        self.rp_10_11.raise_()
        self.rp_11_12.raise_()
        self.spinButton.raise_()
        self.label.raise_()
        self.graphicsView.raise_()
        self.tw_1.raise_()
        self.leaveButton.raise_()
        self.s_3.raise_()
        self.s_2.raise_()
        self.s_1.raise_()
        self.s_4.raise_()
        self.s_6.raise_()
        self.s_7.raise_()
        self.s_9.raise_()
        self.s_12.raise_()
        self.s_10.raise_()
        self.s_13.raise_()
        self.s_15.raise_()
        self.s_16.raise_()
        self.s_18.raise_()
        self.s_19.raise_()
        self.s_21.raise_()
        self.s_22.raise_()
        self.s_24.raise_()
        self.s_25.raise_()
        self.s_27.raise_()
        self.s_28.raise_()
        self.s_30.raise_()
        self.s_31.raise_()
        self.s_33.raise_()
        self.s_34.raise_()
        self.s_36.raise_()
        self.s_5.raise_()
        self.s_8.raise_()
        self.s_11.raise_()
        self.s_14.raise_()
        self.s_17.raise_()
        self.s_20.raise_()
        self.s_23.raise_()
        self.s_26.raise_()
        self.s_29.raise_()
        self.s_32.raise_()
        self.s_35.raise_()
        self.p_9_12.raise_()
        self.p_8_9.raise_()
        self.p_8_11.raise_()
        self.p_7_8.raise_()
        self.p_7_10.raise_()
        self.p_6_9.raise_()
        self.p_5_8.raise_()
        self.p_5_6.raise_()
        self.p_4_7.raise_()
        self.p_4_5.raise_()
        self.p_3_6.raise_()
        self.p_35_36.raise_()
        self.p_34_35.raise_()
        self.p_33_36.raise_()
        self.p_32_35.raise_()
        self.p_32_33.raise_()
        self.p_31_34.raise_()
        self.p_31_32.raise_()
        self.p_30_33.raise_()
        self.p_2_5.raise_()
        self.p_2_3.raise_()
        self.p_29_32.raise_()
        self.p_29_30.raise_()
        self.p_28_31.raise_()
        self.p_28_29.raise_()
        self.p_27_30.raise_()
        self.p_26_29.raise_()
        self.p_26_27.raise_()
        self.p_25_28.raise_()
        self.p_25_26.raise_()
        self.p_24_27.raise_()
        self.p_23_26.raise_()
        self.p_23_24.raise_()
        self.p_22_25.raise_()
        self.p_22_23.raise_()
        self.p_21_24.raise_()
        self.p_20_23.raise_()
        self.p_20_21.raise_()
        self.p_1_4.raise_()
        self.p_1_2.raise_()
        self.p_19_22.raise_()
        self.p_19_20.raise_()
        self.p_18_21.raise_()
        self.p_17_20.raise_()
        self.p_17_18.raise_()
        self.p_16_19.raise_()
        self.p_16_17.raise_()
        self.p_15_18.raise_()
        self.p_14_17.raise_()
        self.p_14_15.raise_()
        self.p_13_16.raise_()
        self.p_13_14.raise_()
        self.p_12_15.raise_()
        self.p_11_14.raise_()
        self.p_11_12.raise_()
        self.p_10_13.raise_()
        self.p_10_11.raise_()
        self.s_0.raise_()
        self.tr_0_1_2.raise_()
        self.tr_0_2_3.raise_()
        self.q_1_2_4_5.raise_()
        self.q_2_3_5_6.raise_()
        self.q_4_5_7_8.raise_()
        self.q_5_6_8_9.raise_()
        self.q_8_9_11_12.raise_()
        self.q_7_8_10_11.raise_()
        self.q_13_14_16_17.raise_()
        self.q_14_15_17_18.raise_()
        self.q_10_11_13_14.raise_()
        self.q_11_12_14_15.raise_()
        self.q_17_18_20_21.raise_()
        self.q_16_17_19_20.raise_()
        self.q_19_20_22_23.raise_()
        self.q_20_21_23_24.raise_()
        self.q_22_23_25_26.raise_()
        self.q_23_24_26_27.raise_()
        self.q_25_26_28_29.raise_()
        self.q_26_27_29_30.raise_()
        self.q_28_29_31_32.raise_()
        self.q_29_30_32_33.raise_()
        self.q_31_32_34_35.raise_()
        self.q_32_33_35_36.raise_()
        self.h_1.raise_()
        self.h_2.raise_()
        self.even.raise_()
        self.odd.raise_()
        self.red.raise_()
        self.black.raise_()
        self.tw_2.raise_()
        self.tw_3.raise_()
        self.c_1.raise_()
        self.c_2.raise_()
        self.c_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.totalLabel.setText(_translate("Form", "My Total: "))
        self.spinButton.setText(_translate("Form", "SPIN!!!"))
        self.leaveButton.setText(_translate("Form", "Leave"))
