# Form implementation generated from reading ui file 'roulette.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RouletteScreen(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: #0f6d39;")
        self.tableLabel = QtWidgets.QLabel(parent=Form)
        self.tableLabel.setGeometry(QtCore.QRect(-70, -90, 941, 511))
        self.tableLabel.setText("")
        self.tableLabel.setPixmap(QtGui.QPixmap("../assets/table.jpg"))
        self.tableLabel.setScaledContents(True)
        self.tableLabel.setObjectName("tableLabel")
        self.wheelLabel = QtWidgets.QLabel(parent=Form)
        self.wheelLabel.setGeometry(QtCore.QRect(520, 321, 291, 291))
        self.wheelLabel.setText("")
        self.wheelLabel.setPixmap(QtGui.QPixmap("../assets/wheel.png"))
        self.wheelLabel.setScaledContents(True)
        self.wheelLabel.setObjectName("wheelLabel")
        self.totalLabel = QtWidgets.QLabel(parent=Form)
        self.totalLabel.setGeometry(QtCore.QRect(10, 340, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(20)
        self.totalLabel.setFont(font)
        self.totalLabel.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"            stop:0 #7d7a7a, \n"
"            stop:1 #c7bfbf);\n"
"            color: black;\n"
"}")
        self.totalLabel.setObjectName("totalLabel")
        self.theDirtySolution = QtWidgets.QLabel(parent=Form)
        self.theDirtySolution.setGeometry(QtCore.QRect(-10, 410, 531, 231))
        self.theDirtySolution.setText("")
        self.theDirtySolution.setObjectName("theDirtySolution")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.totalLabel.setText(_translate("Form", "My Total: "))
