# Form implementation generated from reading ui file '..\..\qt-design-files\sabacc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SabaccScreen(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(799, 598)
        self.graphicsView = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.graphicsView.setObjectName("graphicsView")
        self.leaveButton = QtWidgets.QPushButton(parent=Form)
        self.leaveButton.setGeometry(QtCore.QRect(10, 540, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(15)
        self.leaveButton.setFont(font)
        self.leaveButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    color: white;\n"
"}")
        self.leaveButton.setObjectName("leaveButton")
        self.dealButton = QtWidgets.QPushButton(parent=Form)
        self.dealButton.setGeometry(QtCore.QRect(90, 540, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(15)
        self.dealButton.setFont(font)
        self.dealButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #64ff00,\n"
"        stop:1 #7d9d00\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #64ff00,\n"
"        stop:1 #7d9d00\n"
"    );\n"
"    color: white;\n"
"}")
        self.dealButton.setObjectName("dealButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.leaveButton.setText(_translate("Form", "Leave"))
        self.dealButton.setText(_translate("Form", "Deal!"))
