# Form implementation generated from reading ui file '..\..\qt-design-files\sabacc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(799, 598)
        self.graphicsView = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.graphicsView.setObjectName("graphicsView")
        self.leaveButton = QtWidgets.QPushButton(parent=Form)
        self.leaveButton.setGeometry(QtCore.QRect(10, 540, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        font.setBold(True)
        self.leaveButton.setFont(font)
        self.leaveButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff0000,\n"
"        stop:1 #7d0000\n"
"    );\n"
"    color: white;\n"
"}")
        self.leaveButton.setObjectName("leaveButton")
        self.StartButton = QtWidgets.QPushButton(parent=Form)
        self.StartButton.setGeometry(QtCore.QRect(90, 540, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        font.setBold(True)
        self.StartButton.setFont(font)
        self.StartButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #64ff00,\n"
"        stop:1 #7d9d00\n"
"    );\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #64ff00,\n"
"        stop:1 #7d9d00\n"
"    );\n"
"    color: white;\n"
"}")
        self.StartButton.setObjectName("StartButton")
        self.bet5 = QtWidgets.QPushButton(parent=Form)
        self.bet5.setGeometry(QtCore.QRect(10, 500, 75, 24))
        self.bet5.setObjectName("bet5")
        self.bet50 = QtWidgets.QPushButton(parent=Form)
        self.bet50.setGeometry(QtCore.QRect(10, 460, 75, 24))
        self.bet50.setObjectName("bet50")
        self.dice1 = QtWidgets.QLCDNumber(parent=Form)
        self.dice1.setGeometry(QtCore.QRect(10, 50, 64, 23))
        self.dice1.setObjectName("dice1")
        self.dice2 = QtWidgets.QLCDNumber(parent=Form)
        self.dice2.setGeometry(QtCore.QRect(10, 80, 64, 23))
        self.dice2.setObjectName("dice2")
        self.bet100 = QtWidgets.QPushButton(parent=Form)
        self.bet100.setGeometry(QtCore.QRect(10, 420, 75, 24))
        self.bet100.setObjectName("bet100")
        self.rules = QtWidgets.QPushButton(parent=Form)
        self.rules.setGeometry(QtCore.QRect(90, 500, 75, 24))
        self.rules.setObjectName("rules")
        self.betAmount = QtWidgets.QLCDNumber(parent=Form)
        self.betAmount.setGeometry(QtCore.QRect(100, 460, 64, 23))
        self.betAmount.setObjectName("betAmount")
        self.sabacc_pot = QtWidgets.QLCDNumber(parent=Form)
        self.sabacc_pot.setGeometry(QtCore.QRect(410, 380, 64, 23))
        self.sabacc_pot.setObjectName("sabacc_pot")
        self.drawButton = QtWidgets.QPushButton(parent=Form)
        self.drawButton.setGeometry(QtCore.QRect(670, 430, 75, 24))
        self.drawButton.setObjectName("drawButton")
        self.swapButton = QtWidgets.QPushButton(parent=Form)
        self.swapButton.setGeometry(QtCore.QRect(670, 470, 75, 24))
        self.swapButton.setObjectName("swapButton")
        self.standButton = QtWidgets.QPushButton(parent=Form)
        self.standButton.setGeometry(QtCore.QRect(670, 510, 75, 24))
        self.standButton.setObjectName("standButton")
        self.junkButton = QtWidgets.QPushButton(parent=Form)
        self.junkButton.setGeometry(QtCore.QRect(670, 550, 75, 24))
        self.junkButton.setObjectName("junkButton")
        self.UserDialogBox = QtWidgets.QTextBrowser(parent=Form)
        self.UserDialogBox.setGeometry(QtCore.QRect(270, 551, 256, 31))
        self.UserDialogBox.setObjectName("UserDialogBox")
        self.gamePot = QtWidgets.QLCDNumber(parent=Form)
        self.gamePot.setGeometry(QtCore.QRect(290, 380, 64, 23))
        self.gamePot.setObjectName("gamePot")
        self.deckback = QtWidgets.QLabel(parent=Form)
        self.deckback.setGeometry(QtCore.QRect(290, 220, 80, 120))
        self.deckback.setText("")
        self.deckback.setPixmap(QtGui.QPixmap("..\\..\\qt-design-files\\../assets/sabaac_cards/sabacc_deck_back.png"))
        self.deckback.setScaledContents(True)
        self.deckback.setObjectName("deckback")
        self.oppcount = QtWidgets.QSpinBox(parent=Form)
        self.oppcount.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        self.oppcount.setFont(font)
        self.oppcount.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.oppcount.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.oppcount.setMinimum(1)
        self.oppcount.setMaximum(3)
        self.oppcount.setProperty("value", 3)
        self.oppcount.setObjectName("oppcount")
        self.opplabel = QtWidgets.QLabel(parent=Form)
        self.opplabel.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        self.opplabel.setFont(font)
        self.opplabel.setAutoFillBackground(False)
        self.opplabel.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: black;")
        self.opplabel.setObjectName("opplabel")
        self.chewie = QtWidgets.QLabel(parent=Form)
        self.chewie.setGeometry(QtCore.QRect(30, 230, 121, 81))
        self.chewie.setText("")
        self.chewie.setPixmap(QtGui.QPixmap("..\\..\\qt-design-files\\../assets/sabacc_ops/chewbacca.jpg"))
        self.chewie.setScaledContents(True)
        self.chewie.setObjectName("chewie")
        self.han = QtWidgets.QLabel(parent=Form)
        self.han.setGeometry(QtCore.QRect(620, 220, 111, 101))
        self.han.setAutoFillBackground(False)
        self.han.setText("")
        self.han.setPixmap(QtGui.QPixmap("..\\..\\qt-design-files\\../assets/sabacc_ops/han.png"))
        self.han.setScaledContents(True)
        self.han.setObjectName("han")
        self.lando = QtWidgets.QLabel(parent=Form)
        self.lando.setGeometry(QtCore.QRect(310, 50, 101, 91))
        self.lando.setText("")
        self.lando.setPixmap(QtGui.QPixmap("..\\..\\qt-design-files\\../assets/sabacc_ops/lando.png"))
        self.lando.setScaledContents(True)
        self.lando.setObjectName("lando")
        self.discard_spot = QtWidgets.QLabel(parent=Form)
        self.discard_spot.setGeometry(QtCore.QRect(290, 220, 101, 121))
        self.discard_spot.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"color:  rgba(0, 0, 0,0);")
        self.discard_spot.setObjectName("discard_spot")
        self.Chewbaccachips = QtWidgets.QLabel(parent=Form)
        self.Chewbaccachips.setGeometry(QtCore.QRect(30, 310, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(True)
        self.Chewbaccachips.setFont(font)
        self.Chewbaccachips.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,0);")
        self.Chewbaccachips.setObjectName("Chewbaccachips")
        self.Landochips = QtWidgets.QLabel(parent=Form)
        self.Landochips.setGeometry(QtCore.QRect(310, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(True)
        self.Landochips.setFont(font)
        self.Landochips.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,0);")
        self.Landochips.setObjectName("Landochips")
        self.Hanchips = QtWidgets.QLabel(parent=Form)
        self.Hanchips.setGeometry(QtCore.QRect(620, 320, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(True)
        self.Hanchips.setFont(font)
        self.Hanchips.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,0);")
        self.Hanchips.setObjectName("Hanchips")
        self.card1 = QtWidgets.QPushButton(parent=Form)
        self.card1.setGeometry(QtCore.QRect(200, 425, 80, 120))
        self.card1.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.card1.setText("")
        self.card1.setObjectName("card1")
        self.card2 = QtWidgets.QPushButton(parent=Form)
        self.card2.setGeometry(QtCore.QRect(285, 425, 80, 120))
        self.card2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.card2.setText("")
        self.card2.setObjectName("card2")
        self.card3 = QtWidgets.QPushButton(parent=Form)
        self.card3.setGeometry(QtCore.QRect(370, 425, 80, 120))
        self.card3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.card3.setText("")
        self.card3.setObjectName("card3")
        self.card4 = QtWidgets.QPushButton(parent=Form)
        self.card4.setGeometry(QtCore.QRect(455, 425, 80, 120))
        self.card4.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.card4.setText("")
        self.card4.setObjectName("card4")
        self.card5 = QtWidgets.QPushButton(parent=Form)
        self.card5.setGeometry(QtCore.QRect(540, 425, 80, 120))
        self.card5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 60);\n"
"}")
        self.card5.setText("")
        self.card5.setObjectName("card5")
        self.graphicsView.raise_()
        self.UserDialogBox.raise_()
        self.leaveButton.raise_()
        self.StartButton.raise_()
        self.bet5.raise_()
        self.bet50.raise_()
        self.dice1.raise_()
        self.dice2.raise_()
        self.bet100.raise_()
        self.rules.raise_()
        self.betAmount.raise_()
        self.sabacc_pot.raise_()
        self.drawButton.raise_()
        self.swapButton.raise_()
        self.standButton.raise_()
        self.junkButton.raise_()
        self.gamePot.raise_()
        self.deckback.raise_()
        self.oppcount.raise_()
        self.opplabel.raise_()
        self.chewie.raise_()
        self.han.raise_()
        self.lando.raise_()
        self.discard_spot.raise_()
        self.Chewbaccachips.raise_()
        self.Landochips.raise_()
        self.Hanchips.raise_()
        self.card1.raise_()
        self.card2.raise_()
        self.card3.raise_()
        self.card4.raise_()
        self.card5.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.leaveButton.setText(_translate("Form", "Leave"))
        self.StartButton.setText(_translate("Form", "Start"))
        self.bet5.setText(_translate("Form", "Bet +5"))
        self.bet50.setText(_translate("Form", "Bet +50"))
        self.bet100.setText(_translate("Form", "Bet +100"))
        self.rules.setText(_translate("Form", "Rules"))
        self.drawButton.setText(_translate("Form", "Draw"))
        self.swapButton.setText(_translate("Form", "Swap"))
        self.standButton.setText(_translate("Form", "Stand"))
        self.junkButton.setText(_translate("Form", "Junk"))
        self.UserDialogBox.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.opplabel.setText(_translate("Form", "Opponents:"))
        self.discard_spot.setText(_translate("Form", "TextLabel"))
        self.Chewbaccachips.setText(_translate("Form", "Chips:"))
        self.Landochips.setText(_translate("Form", "Chips:"))
        self.Hanchips.setText(_translate("Form", "Chips:"))
